#! /usr/bin/env bash

# config dirs
CONF="$HOME/.config/daynote/daynote.conf"
STARTUP_FILE="$HOME/.config/daynote/startup.txt"

DIR=$(pwd)
DATE=$(date +"%m-%d-%y")
CMD="vim"
EXT="md"
DEFAULT_STARTUP="goals for today\n- \n\ndone today\n- \n\ngoing forward\n- "

DEBUG=false
if [[ "$1" = "-d" ]]; then
  DEBUG=true
fi

get_config_prop() {
  echo "$(grep -oE "$1=\w+" "$CONF" | cut -d'=' -f2)"
}

if [[ -f "$CONF" ]]; then
  if [[ $DEBUG == true ]]; then
    echo "found $CONF"
    echo ">>>>>>"
    cat "$CONF"
    echo "<<<<<<"
  fi

  CMD=$(get_config_prop "cmd")
  TEMP_EXT=$(get_config_prop "ext")
  if [[ "$TEMP_EXT" != "" ]]; then
    EXT="$TEMP_EXT"
  fi
fi

FILENAME="$DATE.$EXT"

if [[ "$1" = "rm" ]]; then
  if [[ -f "$DIR/$FILENAME" ]]; then
    rm "$DIR/$FILENAME"
    exit 0
  fi
elif [[ "$1" = "-d" ]]; then
  DEBUG=true
fi

if [[ -f "$DIR/$FILENAME" ]]; then
  echo "$FILENAME exists"
else
  echo "creating $FILENAME"
  if [[ -f "$STARTUP_FILE" ]]; then
    cp "$STARTUP_FILE" "$FILENAME"
  else
    echo -e "$DEFAULT_STARTUP" >> "$FILENAME"
  fi
fi

if [[ -n "$CMD" ]]; then
  if [[ $DEBUG == true ]]; then
    echo "opening with $CMD"
  fi

  eval "$CMD $FILENAME"
fi
