#! /usr/bin/env bash

# config dirs
conf="$HOME/.config/daynote/daynote.conf"
startup_file="$HOME/.config/daynote/startup.txt"

dir=$(pwd)
date=$(date +"%m-%d-%y")
cmd="vim"
ext="md"
default_startup="goals for today\n- \n\ndone today\n- \n\ngoing forward\n- "

debug=false
if [[ "$1" = "-d" ]]; then
  debug=true
fi

get_config_prop() {
  echo "$(grep -oE "$1=\w+" "$conf" | cut -d'=' -f2)"
}

get_startup_content() {
  if [[ -f "$startup_file" ]]; then
    cat "$startup_file"
  else
    echo -e "$default_startup"
  fi
}

if [[ -f "$conf" ]]; then
  if [[ $debug == true ]]; then
    echo "found $conf"
    echo ">>>>>>"
    cat "$conf"
    echo "<<<<<<"
  fi

  cmd=$(get_config_prop "cmd")
  temp_ext=$(get_config_prop "ext")
  if [[ "$temp_ext" != "" ]]; then
    ext="$temp_ext"
  fi
fi

filename="$date.$ext"

if [[ "$1" = "rm" ]]; then
  if [[ -f "$dir/$filename" ]]; then
    contents="$(cat "$dir/$filename")"

    if [[ "$contents" != "$(get_startup_content)" ]]; then
      echo "this file has changes in it, are you sure you want to delete (y/n)?"
      read res
      if [[ "$res" == "y" ]]; then
      echo "removing $filename"
        rm "$dir/$filename"
      fi
    else
      echo "removing $filename"
      rm "$dir/$filename"
    fi

    exit 0
  fi
elif [[ "$1" = "-d" ]]; then
  debug=true
fi

if [[ -f "$dir/$filename" ]]; then
  echo "$filename exists"
else
  echo "creating $filename"
  if [[ -f "$startup_file" ]]; then
    cp "$startup_file" "$filename"
  else
    echo -e "$default_startup" >> "$filename"
  fi
fi

if [[ -n "$cmd" ]]; then
  if [[ $debug == true ]]; then
    echo "opening with $cmd"
  fi

  eval "$cmd $filename"
fi
